# -*- coding: utf-8 -*-
"""labphy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/133OqS0lrIA2n9GBSVz_MdGsqlIL5Z94j
"""

import streamlit as st
import matplotlib.pyplot as plt
import numpy as np

# Judul aplikasi
st.title("🔬 Laboratorium Interaktif Pythagoras")

# Sidebar dengan instruksi
with st.sidebar:
    st.header("📘 Menu")
    if st.button("📌 Cara Menggunakan"):
        st.markdown("""
        ### Langkah-Langkah Menggunakan Laboratorium Pythagoras:
        1. Geser slider untuk mengatur panjang sisi siku-siku `a` dan `b`.
        2. Aplikasi akan menghitung sisi miring `c` secara otomatis menggunakan rumus:
           \n    **c = √(a² + b²)**
        3. Lihat visual segitiga siku-siku dan nilai `c` pada grafik.
        4. Gunakan ini untuk memahami hubungan antara sisi-sisi pada segitiga siku-siku.
        """)

# Input panjang sisi a dan b
st.subheader("🔧 Atur Panjang Sisi")
a = st.slider("Panjang sisi a (alas)", min_value=1, max_value=50, value=3)
b = st.slider("Panjang sisi b (tinggi)", min_value=1, max_value=50, value=4)

# Hitung sisi miring c
c = round((a**2 + b**2) ** 0.5, 2)

st.write(f"📏 Panjang sisi miring (c): **{c}** satuan")

# Gambar segitiga
fig, ax = plt.subplots()
ax.plot([0, a, 0, 0], [0, 0, b, 0], color='blue')  # segitiga
ax.plot([a, 0], [0, b], 'r--', label=f'c = {c}')   # sisi miring
ax.text(a/2, -1, f'a = {a}', ha='center', va='top')
ax.text(-1, b/2, f'b = {b}', ha='right', va='center')
ax.text(a/2, b/2, f'c = {c}', color='red', ha='center', va='bottom')

ax.set_aspect('equal')
ax.set_xlim(-5, max(10, a + 5))
ax.set_ylim(-5, max(10, b + 5))
ax.set_title("Visualisasi Segitiga Siku-Siku")
ax.grid(True)
st.pyplot(fig)