# -*- coding: utf-8 -*-
"""convertPDF.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1cpi5q3dSHdUtay_v4_2J7tg3Ad8T0gCV
"""
import streamlit as st
import pdfplumber
from docx import Document
import pandas as pd
from io import BytesIO

st.title("📄 PDF Converter: Word / Excel")
st.write("Upload file PDF lalu pilih mau diubah ke **Word (.docx)** atau **Excel (.xlsx)**")

uploaded_file = st.file_uploader("Unggah PDF", type=["pdf"])

def pdf_to_word(pdf_file):
    doc = Document()
    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if text:
                doc.add_paragraph(text)
    # Simpan ke buffer memory
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer

def pdf_to_excel(pdf_file):
    all_tables = []
    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            tables = page.extract_tables()
            for table in tables:
                df = pd.DataFrame(table[1:], columns=table[0])
                all_tables.append(df)
    
    buffer = BytesIO()
    with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
        if all_tables:
            for i, df in enumerate(all_tables):
                df.to_excel(writer, sheet_name=f"Tabel_{i+1}", index=False)
        else:
            # Jika tidak ada tabel, tulis info
            pd.DataFrame([["Tidak ada tabel ditemukan"]]).to_excel(writer, index=False)
    buffer.seek(0)
    return buffer

if uploaded_file:
    option = st.radio("Pilih format output:", ["Word (.docx)", "Excel (.xlsx)"])
    
    if st.button("Convert"):
        if option == "Word (.docx)":
            result = pdf_to_word(uploaded_file)
            st.success("✅ PDF berhasil dikonversi ke Word!")
            st.download_button(
                label="⬇️ Download Word",
                data=result,
                file_name="converted.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            )
        else:
            result = pdf_to_excel(uploaded_file)
            st.success("✅ PDF berhasil dikonversi ke Excel!")
            st.download_button(
                label="⬇️ Download Excel",
                data=result,
                file_name="converted.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
