# -*- coding: utf-8 -*-
"""buahjatuh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1em6YEhTk1ya9ZaBlEuAQo_izHw9CVbXe
"""

import streamlit as st
import random
from PIL import Image
import time

# Atur halaman
st.set_page_config(page_title="Game Buah Jatuh", layout="centered")

# Load gambar
apple = Image.open("apple.png").resize((50, 50))
bomb = Image.open("bomb.png").resize((50, 50))
player = Image.open("player.png").resize((80, 50))

# Setup
WIDTH = 10  # jumlah kolom
HEIGHT = 10  # jumlah baris
SPEED = 0.5  # detik per frame

# State default
if "player_x" not in st.session_state:
    st.session_state.player_x = WIDTH // 2
    st.session_state.objects = []
    st.session_state.score = 0
    st.session_state.game_over = False

# Tombol kontrol
col1, col2, col3 = st.columns(3)
with col1:
    if st.button("⬅️") and not st.session_state.game_over:
        st.session_state.player_x = max(0, st.session_state.player_x - 1)
with col3:
    if st.button("➡️") and not st.session_state.game_over:
        st.session_state.player_x = min(WIDTH - 1, st.session_state.player_x + 1)
with col2:
    if st.button("🔄 Restart"):
        st.session_state.player_x = WIDTH // 2
        st.session_state.objects = []
        st.session_state.score = 0
        st.session_state.game_over = False

# Tambah objek jatuh
if not st.session_state.game_over and random.random() < 0.2:
    new_obj = {
        "x": random.randint(0, WIDTH - 1),
        "y": 0,
        "type": random.choice(["apple", "bomb"])
    }
    st.session_state.objects.append(new_obj)

# Update posisi objek
new_objects = []
for obj in st.session_state.objects:
    obj["y"] += 1
    if obj["y"] >= HEIGHT - 1:
        if obj["x"] == st.session_state.player_x:
            if obj["type"] == "apple":
                st.session_state.score += 1
            else:
                st.session_state.game_over = True
                st.error("💥 Kena bom! Game Over!")
        else:
            new_objects.append(obj)
    elif obj["y"] < HEIGHT:
        new_objects.append(obj)
st.session_state.objects = new_objects

# Gambar papan
grid = [["" for _ in range(WIDTH)] for _ in range(HEIGHT)]
for obj in st.session_state.objects:
    if 0 <= obj["y"] < HEIGHT:
        grid[obj["y"]][obj["x"]] = apple if obj["type"] == "apple" else bomb
grid[HEIGHT - 1][st.session_state.player_x] = player

# Tampilkan papan
for row in grid:
    cols = st.columns(WIDTH)
    for i, cell in enumerate(row):
        if isinstance(cell, Image.Image):
            cols[i].image(cell)
        else:
            cols[i].write(" ")

# Skor
st.markdown(f"### Skor: {st.session_state.score}")
if not st.session_state.game_over:
    time.sleep(SPEED)
    st.experimental_rerun()