# -*- coding: utf-8 -*-
"""kalkulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hb-SzVakEssTYfF6BDurdBiupcmFBYdR
"""

import streamlit as st

# Fungsi konversi suhu
def convert_temperature(value, from_unit, to_unit):
    if from_unit == to_unit:
        return value

    # Konversi ke Celsius terlebih dahulu
    if from_unit == "Fahrenheit":
        value = (value - 32) * 5 / 9
    elif from_unit == "Kelvin":
        value = value - 273.15

    # Konversi dari Celsius ke target
    if to_unit == "Fahrenheit":
        return value * 9 / 5 + 32
    elif to_unit == "Kelvin":
        return value + 273.15
    else:
        return value  # Tetap Celsius

# Konfigurasi halaman
st.set_page_config(page_title="Kalkulator Suhu", page_icon="🌡️", layout="centered")

# UI
st.title("🌡️ Kalkulator Suhu")
st.write("Konversi suhu antara **Celsius**, **Fahrenheit**, dan **Kelvin**")

# Input pengguna
temp_input = st.number_input("Masukkan suhu:", format="%.2f")
from_unit = st.selectbox("Dari satuan:", ["Celsius", "Fahrenheit", "Kelvin"])
to_unit = st.selectbox("Ke satuan:", ["Celsius", "Fahrenheit", "Kelvin"])

# Tombol konversi
if st.button("Konversi"):
    result = convert_temperature(temp_input, from_unit, to_unit)
    st.success(f"{temp_input:.2f}° {from_unit} = {result:.2f}° {to_unit}")