# -*- coding: utf-8 -*-
"""cosinusapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kkfDvdWQYISZ4ANkVTakKz8MiKpVkUEq
"""

import streamlit as st
import math

# Konfigurasi halaman
st.set_page_config(page_title="Kalkulator Jarak Trigonometri", page_icon="📐")

# Judul aplikasi
st.title("📐 Kalkulator Jarak Kota A ke Kota C (via Trigonometri)")
st.write("Hitung jarak langsung dari Kota A ke Kota C berdasarkan jarak A–B, B–C, dan sudut di B.")

# Input pengguna
a = st.number_input("Masukkan jarak dari Kota A ke B (dalam km):", min_value=0.0, step=1.0, value=10.0)
b = st.number_input("Masukkan jarak dari Kota B ke C (dalam km):", min_value=0.0, step=1.0, value=8.0)
theta_deg = st.slider("Masukkan besar sudut di titik B (dalam derajat):", min_value=0, max_value=180, value=60)

# Hitung jarak A ke C menggunakan hukum cosinus
theta_rad = math.radians(theta_deg)
c = math.sqrt(a**2 + b**2 - 2 * a * b * math.cos(theta_rad))

# Output hasil
if st.button("Hitung Jarak Langsung"):
    st.subheader("📏 Hasil Perhitungan:")
    st.success(f"Jarak langsung dari Kota A ke Kota C adalah: {c:.2f} km")

    # Simulasi komentar berdasarkan panjang jarak
    st.subheader("📝 Simulasi Perjalanan:")
    if c < 5:
        st.info("Dekat banget! Bisa ditempuh dengan jalan kaki atau sepeda. 🚶‍♀️🚲")
    elif c < 20:
        st.info("Cukup dekat, cocok ditempuh dengan bus atau motor. 🚌🏍️")
    elif c < 50:
        st.info("Agak jauh, lebih nyaman pakai mobil. 🚗")
    else:
        st.info("Perjalanan jauh, mungkin butuh transportasi cepat! 🚅✈️")