# -*- coding: utf-8 -*-
"""sudoku.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpi5q3dSHdUtay_v4_2J7tg3Ad8T0gCV
"""
import streamlit as st
import numpy as np
import random

st.set_page_config(page_title="🎮 Game Sudoku", layout="centered")

st.title("🧩 Game Sudoku Sederhana")

# Inisialisasi papan sudoku (9x9)
def generate_sudoku():
    from sudoku import Sudoku
    puzzle = Sudoku(3).difficulty(0.5)  # tingkat kesulitan sedang
    return puzzle.board, puzzle.solve().board

if "puzzle" not in st.session_state:
    try:
        from sudoku import Sudoku
        st.session_state["puzzle"], st.session_state["solution"] = generate_sudoku()
        st.session_state["user_input"] = np.copy(st.session_state["puzzle"])
    except ModuleNotFoundError:
        st.error("Silakan install library `sudoku` dengan perintah: `pip install sudoku` di terminal.")
        st.stop()

# Reset tombol
if st.button("🔄 Reset Game"):
    st.session_state["puzzle"], st.session_state["solution"] = generate_sudoku()
    st.session_state["user_input"] = np.copy(st.session_state["puzzle"])

# Tampilkan grid input
def draw_grid():
    for i in range(9):
        cols = st.columns(9)
        for j in range(9):
            cell_value = st.session_state["puzzle"][i][j]
            key = f"{i}-{j}"
            if cell_value != 0:
                cols[j].markdown(f"<div style='padding:8px; background-color:#eee; text-align:center; border-radius:4px'><b>{cell_value}</b></div>", unsafe_allow_html=True)
            else:
                user_input = cols[j].text_input("", value=str(st.session_state["user_input"][i][j]) if st.session_state["user_input"][i][j] != 0 else "",
                                                max_chars=1, key=key)
                try:
                    val = int(user_input)
                    if 1 <= val <= 9:
                        st.session_state["user_input"][i][j] = val
                    else:
                        st.session_state["user_input"][i][j] = 0
                except:
                    st.session_state["user_input"][i][j] = 0

draw_grid()

# Tombol cek solusi
if st.button("✅ Cek Solusi"):
    if np.array_equal(st.session_state["user_input"], st.session_state["solution"]):
        st.success("🎉 Selamat! Kamu berhasil menyelesaikan Sudoku!")
        st.balloons()
    else:
        st.warning("😢 Masih ada yang salah. Coba lagi!")

# Petunjuk
with st.expander("📌 Cara Bermain"):
    st.markdown("""
    - Isilah angka 1 sampai 9 di setiap baris, kolom, dan kotak 3x3 tanpa pengulangan.
    - Kotak abu-abu adalah angka tetap yang tidak bisa diubah.
    - Tekan **Cek Solusi** untuk memeriksa jawabanmu.
    - Tekan **Reset Game** untuk memulai ulang dengan puzzle baru.
    """)
    
