# -*- coding: utf-8 -*-
"""sudoku.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpi5q3dSHdUtay_v4_2J7tg3Ad8T0gCV
"""
import streamlit as st
import numpy as np
import random
from streamlit_extras.let_it_rain import rain

# Fungsi untuk membuat puzzle Sudoku sederhana
def generate_sudoku():
    base_solution = [
        [5,3,4,6,7,8,9,1,2],
        [6,7,2,1,9,5,3,4,8],
        [1,9,8,3,4,2,5,6,7],
        [8,5,9,7,6,1,4,2,3],
        [4,2,6,8,5,3,7,9,1],
        [7,1,3,9,2,4,8,5,6],
        [9,6,1,5,3,7,2,8,4],
        [2,8,7,4,1,9,6,3,5],
        [3,4,5,2,8,6,1,7,9]
    ]
    
    puzzle = np.array(base_solution)
    
    # Hilangkan beberapa angka untuk jadi puzzle
    for _ in range(40):
        i, j = random.randint(0,8), random.randint(0,8)
        puzzle[i][j] = 0
        
    return base_solution, puzzle

# Inisialisasi session state
if "solution" not in st.session_state:
    solution, puzzle = generate_sudoku()
    st.session_state.solution = solution
    st.session_state.puzzle = puzzle

st.title("🧩 Sudoku Game")
st.write("Isi grid Sudoku dan tekan **Cek Jawaban**. Jika benar, akan muncul konfetti! 🎉")

# Tampilan Sudoku grid
grid = []
for i in range(9):
    cols = st.columns(9)
    row = []
    for j in range(9):
        if st.session_state.puzzle[i][j] != 0:
            cols[j].text_input("", str(st.session_state.puzzle[i][j]), disabled=True, key=f"fixed-{i}-{j}")
            row.append(st.session_state.puzzle[i][j])
        else:
            val = cols[j].text_input("", "", max_chars=1, key=f"input-{i}-{j}")
            try:
                row.append(int(val))
            except:
                row.append(0)
    grid.append(row)

# Tombol cek jawaban
if st.button("✅ Cek Jawaban"):
    correct = True
    for i in range(9):
        for j in range(9):
            if grid[i][j] != st.session_state.solution[i][j]:
                correct = False
                break
    
    if correct:
        st.success("Selamat! Sudoku selesai dengan benar! 🎉")
        
        # Konfetti dengan streamlit-extras
        rain(
            emoji="🎉",
            font_size=54,
            falling_speed=5,
            animation_length="5"
        )
    else:
        st.error("Masih ada yang salah. Coba lagi!")

